# Generated by Django 5.2.7 on 2025-11-13 01:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='US', help_text='ISO country code, e.g. US', max_length=2)),
                ('state', models.CharField(blank=True, default='', help_text="State code, e.g. CO. Leave blank for 'any state'.", max_length=8)),
                ('postal_prefix', models.CharField(blank=True, default='', help_text="ZIP / postal prefix (e.g. 800, 802). Leave blank for 'any ZIP'.", max_length=10)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum merchandise subtotal (after discount) for this rule.', max_digits=10)),
                ('max_subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum merchandise subtotal, or null for no upper limit.', max_digits=10, null=True)),
                ('method', models.CharField(default='standard', help_text='e.g. standard, expedited, overnight.', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping price in store currency.', max_digits=10)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority wins when multiple rules match.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority', 'min_subtotal'],
            },
        ),
    ]
