# Generated by Django 5.2.7 on 2025-11-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_stripeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
