# Generated by Django 5.2.7 on 2025-10-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price_retail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_wholesale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('track_stock', models.BooleanField(default=True)),
                ('stock_cached', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
